project:
  type: website

website:
  title: "Te Guo"
  site-url: https://guote.netlify.app/
  description: "Te Guo - Researcher"
  navbar:
    background: "#0b3142"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dkfzphd
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: minimal
    highlight-style: eiffel
    css: styles.css

editor: visual

